export const SALES_WORKFLOW_STATES = [
  "Purchase Order Received",
  "Order Validated",
  "Inventory Reserved",
  "Work Order Created",
  "Pick Ticket Generated",
  "Manufacturing",
  "Packaging",
  "Invoice Generated",
  "Logistics Handoff Created",
  "Service Provider Confirmed Order",
  "Logistics Fulfillment In Progress",
  "Order Received",
  "Order Transmitted to Warehouse",
  "Notify Customer",
  "Pack Items for Shipment",
  "Generate Shipping Label & Documentation",
  "Track Shipment In Transit",
  "Reroute Delivery",
  "Order Arrives at Destination",
  "Customer Receives & Signs POD",
  "BluBook System Updated",
  "Delivered",
] as const;
