export type ServicePackageDefinition = {
  name: string;
  streams: Record<string, string[]>;
};

export const SERVICE_PACKAGES: ServicePackageDefinition[] = [
  {
    name: "Basic",
    streams: {
      "IT Hosting": [
        "Office",
        "10 GB SSD storage",
        "10 GB SSD Databases",
        "100 mailboxes",
        "100 email aliases",
        "3 FTP Accounts",
        "10 multiple Domains",
        "Microsoft 365 Basic",
        "Storage",
        "500 GB Traffic",
        "Extra's",
        "Firewall Protection",
        "Spam filtering",
        "Malware removal",
        "Backup",
        "24/7 monitoring",
        "email setup",
      ],
      "Financial Accounting": [
        "General Book keeping",
        "Annual Financial Statements",
        "Tax Processing",
        "Bank reconciliation",
      ],
      "Human Resources": ["HRM legal compliance"],
      Marketing: [
        "Website",
        "Logo development and refresh",
        "Business Card development and production",
        "Email marketing",
      ],
      "Post Sales Support": [
        "Customer Care",
        "Email support only (Business hours only)",
        "Technical Support",
        "Email support only (Business hours only)",
      ],
      "Sales Ops": ["Quotation Generation", "Order processing", "Invoicing"],
    },
  },
  {
    name: "Basic Flex",
    streams: {
      "IT Hosting": [
        "Office",
        "10 GB SSD storage",
        "10 GB SSD Databases",
        "100 mailboxes",
        "100 email aliases",
        "3 FTP Accounts",
        "10 multiple Domains",
        "Microsoft 365 Basic",
        "Storage",
        "500 GB Traffic",
        "Extra's",
        "Firewall Protection",
        "Spam filtering",
        "Malware removal",
        "Backup",
        "24/7 monitoring",
        "email setup",
      ],
      "Financial Accounting": [
        "General Book keeping",
        "Annual Financial Statements",
        "Tax Processing",
        "Quarterly Tax filing",
        "Bank reconciliation",
        "Monthly P&L",
        "Yearly Balance Sheet",
      ],
      "Human Resources": ["HRM legal compliance", "HRM Policy Development"],
      Marketing: [
        "Website",
        "Logo development and refresh",
        "Business Card development and production",
        "Email marketing",
      ],
      "Post Sales Support": [
        "Customer Care",
        "Email support only (Business hours only)",
        "Technical Support",
        "Email support only (Business hours only)",
      ],
      "Sales Ops": [
        "Quotation Generation",
        "Order processing",
        "Invoicing",
        "Leads Generation",
      ],
    },
  },
  {
    name: "Advanced",
    streams: {
      "IT Hosting": [
        "Office",
        "15 GB SSD storage",
        "20 GB SSD Databases",
        "250 mailboxes",
        "250 email aliases",
        "7 FTP Accounts",
        "25 multiple Domains",
        "Microsoft 365 Business Basic",
        "Storage",
        "1 TB Traffic",
        "Extra's",
        "Firewall Protection",
        "Spam filtering",
        "Malware removal",
        "Backup",
        "24/7 monitoring",
        "email setup",
      ],
      "Financial Accounting": [
        "General Book keeping",
        "Annual Financial Statements",
        "Tax Processing",
        "Bank Reconciliation",
        "Regulatory compliance",
        "Budgeting and cashflow forecasts",
        "Payroll Services",
        "Quarterly Tax filing",
        "Monthly P&L",
        "Yearly Balance Sheet",
      ],
      "Human Resources": [
        "HRM legal compliance",
        "HRM Policy Development",
        "Recruitment and selection",
        "Benefits and compensation",
      ],
      Marketing: [
        "Website",
        "Logo development and refresh",
        "Business Card development and production",
        "Email marketing",
        "Social Media Marketing and analysis",
        "industry research data",
        "Paid Social Ads",
      ],
      "Post Sales Support": [
        "Customer Care",
        "Email support (Business hours only)",
        "Toll free - Extension (Business hours only)",
        "Pool resources",
        "Customer Experience Survey",
        "Technical Support",
        "Email support (Business hours only)",
        "Toll free - Extension (Business hours only)",
        "Pool resources",
        "Customer Experience Survey",
      ],
      "Sales Ops": [
        "Quotation Generation",
        "Order processing",
        "Invoicing",
        "Leads Generation",
        "Pipeline Mgt - tracking Commit and booked",
        "Warehousing, Inventory Mgt and Distribution",
      ],
    },
  },
  {
    name: "Premium",
    streams: {
      "IT Hosting": [
        "Office",
        "20 GB SSD storage",
        "40 GB SSD Databases",
        "500 mailboxes",
        "500 email aliases",
        "15 FTP Accounts",
        "50 multiple Domains",
        "Microsoft 365 Standard",
        "Storage",
        "unlimited Traffic",
        "Extra's",
        "Firewall Protection",
        "Spam filtering",
        "Malware removal",
        "Backup",
        "24/7 monitoring",
        "email setup",
      ],
      "Financial Accounting": [
        "General Book keeping",
        "Financial Statements",
        "Tax Processing",
        "Bank Reconciliation",
        "Regulatory compliance",
        "Budgeting and cashflow forecasts",
        "Payroll Services",
        "Quarterly Tax filing",
        "inventory reconciliation",
        "Financial Planning and analysis",
        "Monthly P&L",
        "Half Yearly Balance Sheet",
      ],
      "Human Resources": [
        "HRM legal compliance",
        "HRM Policy Development",
        "Recruitment and selection",
        "Benefits and compensation",
        "Training",
        "Organisational development and succession planning",
      ],
      Marketing: [
        "Website",
        "Logo development and refresh",
        "Business Card development and production",
        "Email marketing",
        "Social Media Marketing and analysis",
        "Marketing Strategy Development",
        "industry research data",
        "Social responsibility strategy",
        "Above the line strategy",
        "Paid Social Ads",
        "Content Creation and Video",
      ],
      "Post Sales Support": [
        "Customer Care",
        "Email support (Business hours only)",
        "Toll free line - dedicated (Business hours only)",
        "1 dedicated resource",
        "Customer Experience Survey and analysis",
        "IVR reporting",
        "Technical Support",
        "Email support (Business hours only)",
        "Toll free line - dedicated (Business hours only)",
        "1 dedicated resource",
        "Customer Experience Survey and analysis",
        "IVR reporting",
      ],
      "Sales Ops": [
        "Quotation Generation",
        "Order processing",
        "Invoicing",
        "Leads Generation",
        "Pipeline Mgt - tracking Commit and booked",
        "Order tracking and delivery",
      ],
      "Mgt Consulting": ["Net Promoter Score", "Business Strategy"],
      Office: [
        "Office Access",
        "Luxury Pool Hot Seating",
        "Pool Personal Assistants",
        "Free Wifi",
        "General Tea and coffee",
      ],
    },
  },
  {
    name: "Premium Plus",
    streams: {
      "IT Hosting": [
        "Office",
        "20 GB SSD storage",
        "40 GB SSD Databases",
        "500 mailboxes",
        "500 email aliases",
        "15 FTP Accounts",
        "50 multiple Domains",
        "Microsoft 365 Standard",
        "Storage",
        "unlimited Traffic",
        "Extra's",
        "Firewall Protection",
        "Spam filtering",
        "Malware removal",
        "Backup",
        "24/7 monitoring",
        "email setup",
      ],
      "Financial Accounting": [
        "General Book keeping",
        "Financial Statements",
        "Tax Processing",
        "Bank Reconciliation",
        "Regulatory compliance",
        "Budgeting and cashflow forecasts",
        "Payroll Services",
        "Quarterly Tax filing",
        "inventory reconciliation",
        "Financial Planning and analysis",
        "Monthly P&L",
        "Half Yearly Balance Sheet",
      ],
      "Human Resources": [
        "HRM legal compliance",
        "HRM Policy Development",
        "Recruitment and selection",
        "Benefits and compensation",
        "Training",
        "Organisational development and succession planning",
      ],
      Marketing: [
        "Website",
        "Logo development and refresh",
        "Business Card development and production",
        "Email marketing",
        "Social Media Marketing and analysis",
        "Marketing Strategy Development",
        "industry research data",
        "Social responsibility strategy",
        "Above the line strategy",
        "Paid Social Ads",
        "Content Creation and Video",
      ],
      "Post Sales Support": [
        "Customer Care",
        "Email support (Business hours only)",
        "Toll free line - dedicated (Business hours only)",
        "1 dedicated resource",
        "Customer Experience Survey and analysis",
        "IVR reporting",
        "Technical Support",
        "Email support (Business hours only)",
        "Toll free line - dedicated (Business hours only)",
        "1 dedicated resource",
        "Customer Experience Survey and analysis",
        "IVR reporting",
      ],
      "Sales Ops": [
        "Quotation Generation",
        "Order processing",
        "Invoicing",
        "Leads Generation",
        "Pipeline Mgt - tracking Commit and booked",
        "Order tracking and delivery",
      ],
      Legal: [
        "Contract Management - Drafting and negotiating agreements",
        "Intellectual Property Mgt",
        "Corporate Governance",
      ],
      "Mgt Consulting": [
        "Net Promoter Score",
        "Business Strategy",
        "Transformation",
        "Operational Improvement",
      ],
      Office: [
        "Office Access",
        "Luxury Personal Office",
        "Shared Personalized Assistant",
        "Free Wifi",
        "General Tea and coffee",
      ],
    },
  },
];

export type ServicePartner = {
  packageStream: string;
  name: string;
  site: string;
};

export const SERVICE_PARTNERS: ServicePartner[] = [
  { packageStream: "IT Hosting", name: "Afrihost", site: "www.Afrihost.com" },
  {
    packageStream: "IT Hosting",
    name: "Domains.co.za",
    site: "www.domains.co.za",
  },
  {
    packageStream: "Financial Accounting",
    name: "SMTAX",
    site: "www.smtax.co.za",
  },
  {
    packageStream: "Financial Accounting",
    name: "The Bean Counter",
    site: "www.thebeancounter.co.za",
  },
  {
    packageStream: "Human Resources",
    name: "MHRS",
    site: "www.masterhumanresources.co.za",
  },
  {
    packageStream: "Human Resources",
    name: "Hands-On Human Resources",
    site: "www.hohr.co.za",
  },
  {
    packageStream: "Marketing",
    name: "Digital Fox",
    site: "www.digitalfox.co.za",
  },
  {
    packageStream: "Marketing",
    name: "Macrocosm",
    site: "www.macrocosm.co.za",
  },
  {
    packageStream: "Post Sales Support",
    name: "Care Call",
    site: "www.callcentre.co.za",
  },
  {
    packageStream: "Post Sales Support",
    name: "Call Force Outsourcing",
    site: "www.callforceoutsourcing.com",
  },
  {
    packageStream: "Sales Ops",
    name: "Sales Ticks",
    site: "www.salesticks.co.za",
  },
  { packageStream: "Sales Ops", name: "WNS", site: "www.wns.com" },
  { packageStream: "Legal", name: "LEGL", site: "www.legl.online" },
  { packageStream: "Legal", name: "Resolve", site: "www.rslv.co.za" },
  {
    packageStream: "Mgt Consulting",
    name: "Letsema Consulting",
    site: "www.letsema.co.za",
  },
  {
    packageStream: "Mgt Consulting",
    name: "Mthente Research and Consulting",
    site: "www.mthente.co.za",
  },
];
